// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euvgrnfoikrmtavchouw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1dmdybmZvaWtybXRhdmNob3V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDM4NzMsImV4cCI6MjA2MjExOTg3M30.EWt5hELRvJWdOyjhzWqMuvSpKbO7UPyA9Pihl3AE23E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);